# Site settings
title: Ashwin Menon
tagline: .. Blog ..
email: f2009755@pilani.bits-pilani.ac.in
description: > # this means to ignore newlines until "baseurl:"
  Ashwin Menon's personal blog where he details what he's up to. His ideas, thoughts and his actions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ingridmorstrad.github.io" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Ashwin Menon"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
style:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: IngridMorstrad
    # twitter: jekyllrb
    # facebook:
    # gplus: 
    # dribble: 
    # pinterest: 

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: ashwinmenon

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-75060729-1 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
