# Site settings
title: Ashwin Menon
email: ashwin91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ashwin Menon's (Ingrid Morstrad) personal blog where he details what he's up to. His ideas, thoughts and his actions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://IngridMorstrad.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  IngridMorstrad

# Build settings
markdown: kramdown
