# Site settings
name: Ashwin's Blog
description: Ashwin Menon's personal blog where he details what he's up to. His ideas, thoughts and actions.

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://ashwinmenon.com' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

author:
    name: 'Ashwin Menon'
    email: 'silent_nemesis2710@hotmail.com'
    uri: ''

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate

collections:
    - thoughts
    - activities
    - reviews
