theme = "cactus"

[services]
  [services.googleAnalytics]
    id = "G-5ZWXZPBDDK"

googleAnalytics = "G-5ZWXZPBDDK"

copyright = "Ashwin Menon"

title = "Ashwin's blog"

[[menu.main]]

name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[pagination]
  pagerSize = 20
  
[params]
  description = "Hi, I'm Ashwin. This is my little corner of the web. Hope you enjoy your stay. To get updates, [subscribe](https://buttondown.email/AshwinMenon). RSS available [here](https://www.ashwinmenon.com/index.xml)"

  mainSection = "posts"
  showAllPostsOnHomePage = true
  rss = true
  tagsOverview = true

[[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/TheAshwinMenon"

[[params.social]]
  name = "square-envelope"
  link = "https://buttondown.email/AshwinMenon"

