theme = "cactus"

googleAnalytics = "UA-75060729-1"

copyright = "Ashwin Menon"

title = "Ashwin's blog"

[[menu.main]]

name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[params]
  description = "Hi, I'm Ashwin. This is my little corner of the web. Hope you enjoy your stay. Feel free to leave a comment or [subscribe for updates](https://tinyletter.com/9sy9ll9f)! RSS available [here](https://www.ashwinmenon.com/index.xml)"

  mainSection = "posts"
  showAllPostsOnHomePage = true
  rss = true
  tagsOverview = true

[[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/TheAshwinMenon"

[[params.social]]
  name = "mailchimp"
  link = "https://tinyletter.com/9sy9ll9f"

